name: JSON Validation

on:
  push:
    paths:
      - '**/question_catalog.json'
      - '**/question_catalog_schema.json'
      - '**/map_feature_collection.json'
      - '**/map_feature_collection_schema.json'
      - '**/osm_condition_schema.json'
      - '**/expression_schema.json'
  pull_request:
    paths:
      - '**/question_catalog.json'
      - '**/question_catalog_schema.json'
      - '**/map_feature_collection.json'
      - '**/map_feature_collection_schema.json'
      - '**/osm_condition_schema.json'
      - '**/expression_schema.json'

  # Allow running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        
      - name: Install jsonschema validator
        run: pip install jsonschema

      - name: Validate questions JSON
        run: jsonschema --instance 'assets/datasets/question_catalog.json' 'assets/datasets/question_catalog_schema.json'

      - name: Validate map features JSON
        run: jsonschema --instance 'assets/datasets/map_feature_collection.json' 'assets/datasets/map_feature_collection_schema.json'
